src/main/kotlin/com/ojicoin/domain/Cookie.kt
src/main/kotlin/com/ojicoin/domain/CookieTag.kt
src/main/kotlin/com/ojicoin/domain/Inquiry.kt
src/main/kotlin/com/ojicoin/domain/Tag.kt
src/main/kotlin/com/ojicoin/domain/User.kt
src/main/resources/schema.sql

[#FALCON-3] 도메인 기본 설정 추가

---

build.gradle
gradle.properties
src/main/kotlin/com/ojicoin/domain/Cookie.kt
src/main/kotlin/com/ojicoin/domain/CookieTag.kt
src/main/kotlin/com/ojicoin/domain/Inquiry.kt
src/main/kotlin/com/ojicoin/domain/Tag.kt
src/main/kotlin/com/ojicoin/domain/User.kt
src/test/kotlin/com/ojicoin/domain/UserTest.kt

도메인 기본 구조를 잡음
도메인을 어떻게 디비에서 조회해오고 넣을건지 궁금하면 `UserTest`를 참조하면 됨
생성/조회 로직은 Service로 이동 예정

[Nexters/FALCON#3] 도메인 기본 구조 설정

---

.github/workflows/build.yml

[Nexters/FALCON#11] add github actions for gradle build

[Nexters/FALCON#11] add github actions for gradle build

---

src/main/kotlin/com/ojicoin/domain/Cookie.kt
src/main/kotlin/com/ojicoin/domain/ViewCount.kt
src/main/kotlin/com/ojicoin/plugins/Routing.kt
src/test/kotlin/com/ojicoin/DomainTest.kt
src/test/kotlin/com/ojicoin/RoutingTest.kt
src/test/kotlin/com/ojicoin/TestFixture.kt
src/test/kotlin/com/ojicoin/domain/UserTest.kt

ViewCount를 모아놨다가 저장하는 작업은 필요해지면 하겠음
resolves Nexters/FALCON#22

[Nexters/FALCON#22] 특정 쿠키 뷰 조회 이벤트 추가

---

src/main/kotlin/com/ojicoin/cookiepang/controller/InquiryController.kt
src/main/kotlin/com/ojicoin/cookiepang/domain/Inquiry.kt
src/main/kotlin/com/ojicoin/cookiepang/repository/Repository.kt
src/main/kotlin/com/ojicoin/cookiepang/service/InquiryService.kt
src/main/resources/schema.sql
src/test/kotlin/com/ojicoin/cookiepang/repository/RepositoryTest.kt
src/test/kotlin/com/ojicoin/cookiepang/service/InquiryServiceTest.kt

resolve Nexters/FALCON#23
- 유저가 특정 유저에게 cookie 생성 요구하는 로직
- notifiation 기능 추가 예정

[Nexters/FALCON#23] Implement inquiry feature

---

src/main/kotlin/com/ojicoin/cookiepang/controller/UserTagController.kt
src/main/kotlin/com/ojicoin/cookiepang/domain/UserTag.kt
src/main/kotlin/com/ojicoin/cookiepang/repository/Repository.kt
src/main/kotlin/com/ojicoin/cookiepang/service/UserTagService.kt
src/main/resources/schema.sql
src/test/kotlin/com/ojicoin/cookiepang/repository/RepositoryTest.kt
src/test/kotlin/com/ojicoin/cookiepang/service/UserTagServiceTest.kt

resolve Nexters/FALCON#19
- `UserTags` table 생성
- users와 tags 사이에 n:m 관계를 형성함.

[Nexters/FALCON#19] 유저가 선호하는 카테고리 생성

---

build.gradle.kts
gradle.properties
src/main/kotlin/com/ojicoin/cookiepang/controller/ApiController.kt
src/test/kotlin/com/ojicoin/cookiepang/Fixture.kt
src/test/kotlin/com/ojicoin/cookiepang/controller/ApiControllerTest.kt

[Nexters/FALCON#3] RestAssured 와 컨트롤러 테스트 추가

---

src/main/kotlin/com/ojicoin/cookiepang/domain/Cookie.kt
src/main/kotlin/com/ojicoin/cookiepang/event/Event.kt
src/main/kotlin/com/ojicoin/cookiepang/repository/Repository.kt
src/main/kotlin/com/ojicoin/cookiepang/service/CookieService.kt
src/test/kotlin/com/ojicoin/cookiepang/Fixture.kt
src/test/kotlin/com/ojicoin/cookiepang/service/CookieServiceTest.kt

[Nexters/FALCON#21] 쿠키를 불변 객체가 아닌 도메인으로 변경

---

src/main/kotlin/com/ojicoin/cookiepang/controller/ApiController.kt

[NO-ISSUE] Fix creating user categories path in swagger

---

src/main/kotlin/com/ojicoin/cookiepang/controller/ApiController.kt
src/main/kotlin/com/ojicoin/cookiepang/domain/Cookie.kt
src/main/kotlin/com/ojicoin/cookiepang/dto/DomainDto.kt
src/main/kotlin/com/ojicoin/cookiepang/repository/Repository.kt
src/main/kotlin/com/ojicoin/cookiepang/service/CookieService.kt
src/main/resources/schema.sql
src/test/kotlin/com/ojicoin/cookiepang/controller/ApiControllerTest.kt
src/test/kotlin/com/ojicoin/cookiepang/service/CookieServiceTest.kt
src/test/kotlin/com/ojicoin/cookiepang/service/ViewAssemblerTest.kt

[Nexters/FALCON#49] 쿠키 생성 API 추가

---

src/main/kotlin/com/ojicoin/cookiepang/controller/ApiController.kt
src/main/kotlin/com/ojicoin/cookiepang/domain/Cookie.kt
src/main/kotlin/com/ojicoin/cookiepang/service/CookieService.kt
src/test/kotlin/com/ojicoin/cookiepang/service/CookieServiceTest.kt

[Nexters/FALCON#52] 쿠키 제거 API 추가

---

src/main/kotlin/com/ojicoin/cookiepang/controller/ApiController.kt
src/main/kotlin/com/ojicoin/cookiepang/domain/Cookie.kt
src/main/kotlin/com/ojicoin/cookiepang/dto/DomainDto.kt
src/main/kotlin/com/ojicoin/cookiepang/service/CookieService.kt
src/test/kotlin/com/ojicoin/cookiepang/service/CookieServiceTest.kt

[Nexters/FALCON#50] 쿠키 가격 업데이트 추가

---

src/main/kotlin/com/ojicoin/cookiepang/controller/ApiController.kt
src/main/kotlin/com/ojicoin/cookiepang/domain/User.kt
src/main/kotlin/com/ojicoin/cookiepang/dto/DomainDto.kt
src/main/kotlin/com/ojicoin/cookiepang/repository/Repository.kt
src/main/kotlin/com/ojicoin/cookiepang/service/UserService.kt
src/main/resources/schema.sql
src/test/kotlin/com/ojicoin/cookiepang/service/UserServiceTest.kt

resolve Nexters/FALCON#54 about user create api
resolve Nexters/FALCON#64 about user profile background picture

[Nexters/FALCON#54] Implement user create api

---

src/main/kotlin/com/ojicoin/cookiepang/controller/ApiController.kt
src/main/kotlin/com/ojicoin/cookiepang/domain/Ask.kt
src/main/kotlin/com/ojicoin/cookiepang/dto/DomainDto.kt
src/main/kotlin/com/ojicoin/cookiepang/service/AskService.kt
src/test/kotlin/com/ojicoin/cookiepang/service/AskServiceTest.kt

resolve Nexters/FALCON#57
duplicate pr: https://github.com/Nexters/MARS/pull/39

[Nexters/FALCON#57] Implement ask update logic

---

src/main/kotlin/com/ojicoin/cookiepang/dto/ContractDto.kt
src/main/kotlin/com/ojicoin/cookiepang/service/CookieContractService.kt
src/main/resources/application.yml
src/test/kotlin/com/ojicoin/cookiepang/service/CookieContractServiceTest.kt

[Nexters/FALCON#81] cookieId를 통한 이벤트 조회 기능 추가 
- 이벤트 조회시 fromBlock 사용가능한 인터페이스 추가
- 컨트랙 스펙 변경으로 인한 테스트 코드 일부 변경

[Nexters/FALCON#81] cookieId를 통한 이벤트 조회 기능 추가

---

src/main/kotlin/com/ojicoin/cookiepang/dto/ContractDto.kt
src/main/kotlin/com/ojicoin/cookiepang/service/CookieContractService.kt
src/test/kotlin/com/ojicoin/cookiepang/service/CookieContractServiceTest.kt

[Nexters/FALCON#noissue] Event 조회시 blockNumber 추가

[Nexters/FALCON#noissue] Event 조회시 blockNumber 추가

---

src/main/kotlin/com/ojicoin/cookiepang/service/CookieService.kt
src/main/kotlin/com/ojicoin/cookiepang/service/ViewAssembler.kt
src/test/kotlin/com/ojicoin/cookiepang/service/ViewAssemblerTest.kt

[] 쿠키 이벤트 수동으로 발행하도록 수정

---

.github/workflows/build.yml
.gitignore
src/main/kotlin/com/ojicoin/cookiepang/contract/config/CaverConfiguration.kt
src/main/resources/application.yml

[Nexters/FALCON#98] 민감한 정보들 환경변수 사용

[Nexters/FALCON#98] 민감한 정보들 환경변수 사용

---

src/main/kotlin/com/ojicoin/cookiepang/contract/event/EventLog.kt
src/main/kotlin/com/ojicoin/cookiepang/controller/ViewController.kt
src/main/kotlin/com/ojicoin/cookiepang/domain/Cookie.kt
src/main/kotlin/com/ojicoin/cookiepang/domain/CookieHistory.kt
src/main/kotlin/com/ojicoin/cookiepang/repository/Repository.kt
src/main/kotlin/com/ojicoin/cookiepang/service/CookieService.kt
src/main/kotlin/com/ojicoin/cookiepang/service/ViewAssembler.kt
src/main/resources/data.sql
src/main/resources/schema.sql

이벤트 조회 적용함.
blockAddress가 최신이 아닐경우에만 재조회함

[Nexters/FALCON#85] 쿠키 이벤트 조회 적용

---

build.gradle.kts
src/main/kotlin/com/ojicoin/cookiepang/contract/service/CookieContractService.kt
src/main/kotlin/com/ojicoin/cookiepang/contract/service/TransactionService.kt

[Nexters/FALCON#noissue] transaction 정보 조회 및 getPastLog 조회시 fromBlock 받도록 수정

[Nexters/FALCON#noissue] transaction 정보 조회 및 getPastLog 조회시 fromBlock 받도록 수정

---

build.gradle.kts
src/main/kotlin/com/ojicoin/cookiepang/config/CookiepangConfiguration.kt
src/main/kotlin/com/ojicoin/cookiepang/config/StorageProperties.kt
src/main/kotlin/com/ojicoin/cookiepang/controller/ApiController.kt
src/main/kotlin/com/ojicoin/cookiepang/controller/StorageController.kt
src/main/kotlin/com/ojicoin/cookiepang/repository/FileSystemStorageRepository.kt
src/main/kotlin/com/ojicoin/cookiepang/repository/S3Repository.kt
src/main/kotlin/com/ojicoin/cookiepang/repository/StorageRepository.kt
src/main/kotlin/com/ojicoin/cookiepang/service/StorageService.kt
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml

[Nexters/FALCON#97] Integration s3 storage

---

src/main/kotlin/com/ojicoin/cookiepang/config/RetryConfig.kt
src/main/kotlin/com/ojicoin/cookiepang/config/RetryListener.kt
src/main/kotlin/com/ojicoin/cookiepang/contract/service/TransactionService.kt
src/main/kotlin/com/ojicoin/cookiepang/service/RetryService.kt
src/test/kotlin/com/ojicoin/cookiepang/contract/service/TransactionServiceTest.kt

[Nexters/FALCON#noissue] Retry AOP proxy -> retry template 으로 변경

[Nexters/FALCON#noissue] Retry AOP proxy -> retry template 으로 변경

---

src/main/kotlin/com/ojicoin/cookiepang/controller/LoginController.kt
src/main/kotlin/com/ojicoin/cookiepang/controller/UserExistException.kt
src/main/kotlin/com/ojicoin/cookiepang/exception/UserExistException.kt
src/main/kotlin/com/ojicoin/cookiepang/repository/Repository.kt
src/main/kotlin/com/ojicoin/cookiepang/service/UserService.kt
src/test/kotlin/com/ojicoin/cookiepang/service/UserServiceTest.kt

[Nexters/FALCON#53] Implement user auth api for checking duplicate user

---

.github/workflows/build.yml
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application-real.yml
src/main/resources/application.yml

[Nexters/FALCON#noissue] 메인넷 설정정보 real 프로파일에 추가

[Nexters/FALCON#noissue] 메인넷 설정정보 real 프로파일에 추가

---

src/main/kotlin/com/ojicoin/cookiepang/controller/ViewController.kt
src/main/kotlin/com/ojicoin/cookiepang/dto/ViewDto.kt
src/main/kotlin/com/ojicoin/cookiepang/service/ViewAssembler.kt
src/test/kotlin/com/ojicoin/cookiepang/service/ViewAssemblerTest.kt

[] 뷰에 유저 아이디 추가

---

.github/workflows/build.yml
src/main/kotlin/com/ojicoin/cookiepang/contract/config/ContractABI.kt
src/main/kotlin/com/ojicoin/cookiepang/repository/S3Repository.kt
src/main/resources/application-real.yml
src/main/resources/application.yml

[Nexters/FALCON#noissue] profile setup

[Nexters/FALCON#noissue] profile setup

---

build.gradle.kts
src/main/kotlin/com/ojicoin/cookiepang/contract/service/CookieContractService.kt
src/main/kotlin/com/ojicoin/cookiepang/contract/service/TransactionService.kt
src/main/kotlin/com/ojicoin/cookiepang/controller/AskController.kt
src/main/kotlin/com/ojicoin/cookiepang/controller/CategoryController.kt
src/main/kotlin/com/ojicoin/cookiepang/controller/CookieController.kt
src/main/kotlin/com/ojicoin/cookiepang/controller/LoginController.kt
src/main/kotlin/com/ojicoin/cookiepang/controller/UserController.kt
src/main/kotlin/com/ojicoin/cookiepang/controller/ViewController.kt
src/main/kotlin/com/ojicoin/cookiepang/dto/ViewDto.kt
src/main/kotlin/com/ojicoin/cookiepang/exception/ExceptionHandler.kt
src/main/kotlin/com/ojicoin/cookiepang/exception/ParameterizedException.kt
src/main/kotlin/com/ojicoin/cookiepang/exception/UserExistException.kt
src/main/kotlin/com/ojicoin/cookiepang/service/AskService.kt
src/main/kotlin/com/ojicoin/cookiepang/service/CookieService.kt
src/main/kotlin/com/ojicoin/cookiepang/service/UserService.kt
src/test/kotlin/com/ojicoin/cookiepang/service/AskServiceTest.kt
src/test/kotlin/com/ojicoin/cookiepang/service/CookieServiceTest.kt
src/test/kotlin/com/ojicoin/cookiepang/service/UserServiceTest.kt

Swagger @ApiResponse로 응답값 정리하기 귀찮다..

[NEXTERS/FALCON#102] 예외 처리

---

src/main/kotlin/com/ojicoin/cookiepang/config/WebConfiguration.kt

Falcon cors

---

src/main/kotlin/com/ojicoin/cookiepang/contract/service/CookieContractService.kt
src/main/kotlin/com/ojicoin/cookiepang/controller/CookieController.kt
src/main/kotlin/com/ojicoin/cookiepang/dto/DomainDto.kt
src/main/kotlin/com/ojicoin/cookiepang/repository/Repository.kt
src/main/kotlin/com/ojicoin/cookiepang/service/CookieService.kt
src/main/kotlin/com/ojicoin/cookiepang/service/UserService.kt
src/test/kotlin/com/ojicoin/cookiepang/contract/service/CookieContractServiceTest.kt

[Nexters/FALCON#117] Implement default cookie api

---

src/main/kotlin/com/ojicoin/cookiepang/controller/UserController.kt
src/main/kotlin/com/ojicoin/cookiepang/domain/User.kt
src/main/kotlin/com/ojicoin/cookiepang/dto/ViewDto.kt
src/main/kotlin/com/ojicoin/cookiepang/service/UserService.kt
src/main/resources/schema.sql
src/test/kotlin/com/ojicoin/cookiepang/service/UserServiceTest.kt

[Nexters/FALCON#118] 회원가입 완료 여부 확인

[Nexters/FALCON#118] 회원가입 완료 여부 확인

---

src/main/kotlin/com/ojicoin/cookiepang/controller/CategoryController.kt
src/main/kotlin/com/ojicoin/cookiepang/dto/DomainDto.kt
src/main/kotlin/com/ojicoin/cookiepang/dto/ViewDto.kt
src/main/kotlin/com/ojicoin/cookiepang/service/UserCategoryService.kt
src/test/kotlin/com/ojicoin/cookiepang/service/CookieServiceTest.kt
src/test/kotlin/com/ojicoin/cookiepang/service/UserCategoryServiceTest.kt

[Nexters/FALCON#108] Implement get user category by userId api

---

.github/workflows/build.yml
src/main/kotlin/com/ojicoin/cookiepang/config/SpringJdbcConfiguration.kt
src/main/resources/application-dev.yml
src/main/resources/application-real.yml

jdbc:postgresql://cooiepang-db.ctsd0extrjqk.ap-northeast-2.rds.amazonaws.com:5432/cookiepang
jdbc:postgresql://cooiepang-db.ctsd0extrjqk.ap-northeast-2.rds.amazonaws.com:5432/cookiepang-real

[NO-ISSUE] Connect real db

---

src/main/resources/schema.sql

[Nexters/FALCON#noissue] ddl 변경

[Nexters/FALCON#noissue] ddl 변경

---

src/main/kotlin/com/ojicoin/cookiepang/contract/dto/ContractDto.kt
src/main/kotlin/com/ojicoin/cookiepang/contract/service/CookieContractService.kt
src/main/kotlin/com/ojicoin/cookiepang/contract/service/TransactionService.kt
src/main/kotlin/com/ojicoin/cookiepang/service/CookieService.kt
src/main/kotlin/com/ojicoin/cookiepang/service/UserService.kt
src/test/kotlin/com/ojicoin/cookiepang/Fixture.kt
src/test/kotlin/com/ojicoin/cookiepang/contract/service/TransactionServiceTest.kt

[Nexters/FALCON#118] 회원가입 완료시 해머 지급 및 default 쿠키 중복생성 방지

[Nexters/FALCON#118] 회원가입 완료시 해머 지급 및 default 쿠키 중복생성 방지

---

src/main/resources/schema.sql

 [Nexters/FALCON#noissue] ddl 리버트

---

src/main/kotlin/com/ojicoin/cookiepang/contract/controller/ContractCookieController.kt
src/main/kotlin/com/ojicoin/cookiepang/contract/controller/ContractHammerController.kt
src/main/kotlin/com/ojicoin/cookiepang/contract/controller/KlayController.kt
src/main/kotlin/com/ojicoin/cookiepang/contract/dto/ContractDto.kt
src/main/kotlin/com/ojicoin/cookiepang/contract/service/KlayService.kt
src/test/kotlin/com/ojicoin/cookiepang/contract/service/KlayServiceTest.kt

[Nexters/FALCON#118] 클레이튼 balance 조회 API 추가

[Nexters/FALCON#118] 클레이튼 balance 조회 API 추가

---

src/main/kotlin/com/ojicoin/cookiepang/controller/AskController.kt
src/main/kotlin/com/ojicoin/cookiepang/controller/ViewController.kt
src/main/kotlin/com/ojicoin/cookiepang/domain/Ask.kt
src/main/kotlin/com/ojicoin/cookiepang/dto/DomainDto.kt
src/main/kotlin/com/ojicoin/cookiepang/repository/Repository.kt
src/main/kotlin/com/ojicoin/cookiepang/service/AskService.kt
src/main/kotlin/com/ojicoin/cookiepang/service/ViewAssembler.kt
src/main/resources/schema.sql
src/test/kotlin/com/ojicoin/cookiepang/service/AskServiceTest.kt
src/test/kotlin/com/ojicoin/cookiepang/service/CookieServiceTest.kt
src/test/kotlin/com/ojicoin/cookiepang/service/ViewAssemblerTest.kt

- Pagination 지원
- categoryId 추가

[NO-ISSUE] ask 관련 ux 플로우 내용 추가

---

src/main/kotlin/com/ojicoin/cookiepang/dto/ViewDto.kt
src/main/kotlin/com/ojicoin/cookiepang/service/ViewAssembler.kt

[Nexters/FALCON#126] cookie목록 조회시 cookie status 노출, cookie detail 조회시 cookieId 같이 반환

[Nexters/FALCON#126] cookie목록 조회시 cookie status 노출, cookie detail 조회시 cookieId 같이 반환

---

src/main/kotlin/com/ojicoin/cookiepang/contract/controller/ContractCookieController.kt
src/main/kotlin/com/ojicoin/cookiepang/contract/controller/ContractHammerController.kt

[Nexters/FALCON#126] 잔액 조회 API는 balance 오브젝트로 응답 및 API명 수정

[Nexters/FALCON#126] 잔액 조회 API는 balance 오브젝트로 응답 및 API명 수정

---

src/main/kotlin/com/ojicoin/cookiepang/controller/CategoryController.kt

[Nexters/FALCON#126] category 응답 타입 변경

[Nexters/FALCON#126] category 응답 타입 변경

---

src/main/kotlin/com/ojicoin/cookiepang/util/NotificationMessageUtils.kt

```
요청
익명의 누군가 '$쿠키의 질문 명$(15자 이상..처리)'라는 질문을 요청했어요. 쿠키로 만들러 가볼까요?
```
```
요청
익명의 누군가 '$쿠키의 질문 명$(15자 이상..처리)'라는 질문을 요청했어요.
```

[NO-ISSUE] Change notification message

---

src/main/resources/application.yml

[Nexters/FALCON#noissue] max file size 변경

[Nexters/FALCON#noissue] max file size 변경

---

src/main/resources/application-real.yml

[Nexters/FALCON#noissue] 컨트랙 정보 수정

[Nexters/FALCON#noissue] 컨트랙 정보 수정

---

src/main/kotlin/com/ojicoin/cookiepang/contract/service/CookieContractService.kt
src/main/kotlin/com/ojicoin/cookiepang/service/CookieService.kt
src/main/kotlin/com/ojicoin/cookiepang/service/UserService.kt

[Nexters/FALCON#noissue] bugfix

[Nexters/FALCON#noissue] bugfix

---

src/main/kotlin/com/ojicoin/cookiepang/domain/Notification.kt
src/main/kotlin/com/ojicoin/cookiepang/service/NotificationService.kt
src/test/kotlin/com/ojicoin/cookiepang/service/NotificationServiceTest.kt

[Nexters/FALCON#130] Fix notification logic with paging and sorting

---

build.gradle.kts
src/main/kotlin/com/ojicoin/cookiepang/service/FcmService.kt
src/main/kotlin/com/ojicoin/cookiepang/service/PushMessageOperations.kt
src/main/kotlin/com/ojicoin/cookiepang/service/TokenGenerator.kt
src/main/resources/META-INF/spring-configuration-metadata.json
src/main/resources/application.yml
src/test/kotlin/com/ojicoin/cookiepang/service/FcmServiceTest.kt

FCM 보내는 처리 추가
근데 저 firebase 설정파일 넣어주는 게 문제넹

[Nexters/FALCON#132] FCM 전송 구현
